version: '3.7'

services:
  iflow_db:
    image: postgres
    container_name: database_iflow
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=iflow-manager
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_DB=iflow
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local